import Foundation

/// Shared normalization for Windows file-type associations, used by both the
/// MSIX manifest (`AppxManifestGenerator`) and the portable-exe registration
/// scripts (`WindowsBundler`). Windows associates by **file extension**, so
/// these turn a `windows.document_types` entry into the canonical forms each
/// consumer needs.
enum FileAssociationSupport {
    /// Canonicalize declared extensions: trimmed, lowercased, leading dot
    /// ensured, invalid characters dropped, de-duplicated, order preserved.
    /// `"FOO"`, `".foo"`, `" .Foo "` all collapse to `.foo`; empties / dot-only
    /// entries are discarded.
    static func normalizedExtensions(_ raw: [String]) -> [String] {
        var seen = Set<String>()
        var out: [String] = []
        for ext in raw {
            var e = ext.trimmingCharacters(in: .whitespaces).lowercased()
            if e.hasPrefix(".") { e.removeFirst() }
            // A file extension is alphanumerics (plus a rare `-`); strip the rest
            // as defense in depth against a stray path/glob character.
            e = String(e.unicodeScalars.filter { s in
                CharacterSet.alphanumerics.contains(s) || s == "-"
            })
            guard !e.isEmpty else { continue }
            let dotted = "." + e
            if seen.insert(dotted).inserted { out.append(dotted) }
        }
        return out
    }

    /// A valid MSIX `FileTypeAssociation` `Name` (also reused as the portable
    /// ProgID stem): lowercase, `[a-z0-9.-_]`, non-empty. Derived from the
    /// declared `name`, falling back to `filetype<n>` when absent or empty
    /// after sanitizing.
    static func associationName(_ declared: String?, fallbackIndex: Int) -> String {
        let sanitized = (declared ?? "").lowercased().unicodeScalars.filter { s in
            CharacterSet.alphanumerics.contains(s) || s == "." || s == "-" || s == "_"
        }
        let name = String(String.UnicodeScalarView(sanitized))
        return name.isEmpty ? "filetype\(fallbackIndex + 1)" : name
    }

    /// A ProgID for a portable-exe association, e.g. `com.example.app.filetype1`
    /// → the per-user class registered under `HKCU\Software\Classes`.
    static func progID(appID: String, associationName: String) -> String {
        let stem = appID.lowercased().unicodeScalars.filter { s in
            CharacterSet.alphanumerics.contains(s) || s == "." || s == "-" || s == "_"
        }
        let cleaned = String(String.UnicodeScalarView(stem))
        let base = cleaned.isEmpty ? "swiftpwa.app" : cleaned
        return "\(base).\(associationName)"
    }

    /// Generate the portable-exe `register` / `unregister` batch scripts for
    /// the declared document types, or `nil` when none resolve. A portable app
    /// has no installer, so these let the user opt into the `HKCU\Software\`
    /// `Classes` association pointing at the exe **at its current location**
    /// (`%~dp0` = the script's own folder, where the exe sits). Returns `cmd`
    /// bodies (CRLF-joined by the caller when writing).
    static func registrationScripts(
        docTypes: [PWAManifest.ExtensionDocumentType],
        exeName: String,
        appID: String,
        appName: String
    ) -> (register: [String], unregister: [String])? {
        let groups: [(progid: String, friendly: String, exts: [String])] =
            docTypes.enumerated().compactMap { index, dt in
                let exts = normalizedExtensions(dt.extensions)
                guard !exts.isEmpty else { return nil }
                let assoc = associationName(dt.name, fallbackIndex: index)
                let friendly = dt.name ?? "\(appName) document"
                return (progID(appID: appID, associationName: assoc), friendly, exts)
            }
        guard !groups.isEmpty else { return nil }

        var reg = [
            "@echo off",
            "REM Registers this app for its file types (per-user, HKCU).",
            "REM Generated by swift-pwa for the portable build. Run once from",
            "REM the app folder; run unregister-file-types.cmd to undo.",
            "setlocal",
            "set \"EXE=%~dp0\(exeName)\""
        ]
        var unreg = [
            "@echo off",
            "REM Removes the file-type associations registered by register-file-types.cmd.",
            "setlocal"
        ]
        for group in groups {
            let cls = "HKCU\\Software\\Classes\\\(group.progid)"
            reg.append("reg add \"\(cls)\" /ve /d \"\(group.friendly)\" /f")
            reg.append(
                "reg add \"\(cls)\\shell\\open\\command\" /ve /d \"\\\"%EXE%\\\" \\\"%%1\\\"\" /f"
            )
            unreg.append("reg delete \"\(cls)\" /f")
            for ext in group.exts {
                let extKey = "HKCU\\Software\\Classes\\\(ext)"
                reg.append("reg add \"\(extKey)\" /ve /d \"\(group.progid)\" /f")
                unreg.append("reg delete \"\(extKey)\" /f")
            }
        }
        reg.append("echo Registered file types for \(appName).")
        reg.append("echo You may need to sign out and back in for Explorer to refresh.")
        unreg.append("echo Removed file-type associations for \(appName).")
        return (reg, unreg)
    }
}
