import Foundation

/// Shared handling for `url_schemes` — the deep-link schemes an app declares
/// it handles. Every bundler needs the same canonical list, so normalization
/// lives here rather than five times over (the `FileAssociationSupport` shape).
///
/// One list serves all five platforms because a URL scheme is the same string
/// everywhere; only the artifact it lands in differs.
enum URLSchemeSupport {
    /// Canonicalize declared schemes: trimmed, lowercased, a trailing colon or
    /// `://` accepted and dropped, de-duplicated, order preserved. Entries
    /// that aren't schemes are dropped here and rejected with a message by
    /// ``validate(_:)`` — which `swift-pwa build` runs first, so a silent drop
    /// is unreachable in practice.
    static func normalized(_ raw: [String]) -> [String] {
        var seen = Set<String>()
        var out: [String] = []
        for entry in raw {
            let scheme = normalize(entry)
            guard isValid(scheme), seen.insert(scheme).inserted else { continue }
            out.append(scheme)
        }
        return out
    }

    /// Lowercase and strip the punctuation people write around a scheme —
    /// `"MyApp://"`, `"myapp:"` and `"myapp"` are the same declaration, the
    /// same leniency ``ExternalURLPolicy/declare(schemes:)`` applies.
    static func normalize(_ raw: String) -> String {
        raw.trimmingCharacters(in: .whitespaces)
            .lowercased()
            .trimmingCharacters(in: CharacterSet(charactersIn: ":/"))
    }

    /// RFC 3986's scheme grammar: a letter, then letters / digits / `+` `-` `.`.
    static func isValid(_ scheme: String) -> Bool {
        guard let first = scheme.first, first.isLetter else { return false }
        return scheme.allSatisfy { $0.isLetter || $0.isNumber || "+-.".contains($0) }
    }

    /// The schemes a manifest declares, canonical. Empty when the key is unset,
    /// so every generator can call it unconditionally and emit nothing.
    static func declared(_ manifest: PWAManifest) -> [String] {
        normalized(manifest.urlSchemes ?? [])
    }

    /// The portable-exe `register` / `unregister` batch scripts for the
    /// declared schemes, or `nil` when none resolve. The URL-handler
    /// counterpart to ``FileAssociationSupport/registrationScripts(docTypes:exeName:appID:appName:)``
    /// — a portable app has no installer, so registration is a script the user
    /// runs once, writing `HKCU\Software\Classes` entries that point at the
    /// exe **at its current location** (`%~dp0` = the script's own folder).
    ///
    /// A protocol class is shaped unlike a file class: the key *is* the scheme,
    /// its default value is conventionally prefixed `URL:`, and it carries an
    /// empty `URL Protocol` value — that value's *presence* is what marks the
    /// class as a URL handler, so an empty string is load-bearing rather than a
    /// placeholder. `reg add` with `/d ""` writes exactly that.
    static func registrationScripts(
        schemes: [String],
        exeName: String,
        appName: String
    ) -> (register: [String], unregister: [String])? {
        let schemes = normalized(schemes)
        guard !schemes.isEmpty else { return nil }
        var reg = [
            "@echo off",
            "REM Registers this app as the handler for its URL schemes (per-user, HKCU).",
            "REM Generated by swift-pwa for the portable build. Run once from",
            "REM the app folder; run unregister-url-schemes.cmd to undo.",
            "setlocal",
            "set \"EXE=%~dp0\(exeName)\""
        ]
        var unreg = [
            "@echo off",
            "REM Removes the URL-scheme handlers registered by register-url-schemes.cmd.",
            "setlocal"
        ]
        for scheme in schemes {
            let cls = "HKCU\\Software\\Classes\\\(scheme)"
            reg.append("reg add \"\(cls)\" /ve /d \"URL:\(appName)\" /f")
            reg.append("reg add \"\(cls)\" /v \"URL Protocol\" /d \"\" /f")
            reg.append(
                "reg add \"\(cls)\\shell\\open\\command\" /ve /d \"\\\"%EXE%\\\" \\\"%%1\\\"\" /f"
            )
            unreg.append("reg delete \"\(cls)\" /f")
        }
        let listed = schemes.map { "\($0)://" }.joined(separator: ", ")
        reg.append("echo Registered \(listed) for \(appName).")
        unreg.append("echo Removed URL-scheme handlers for \(appName).")
        return (reg, unreg)
    }
}
