#!/usr/bin/env bash
#
# Regenerate Sources/SwiftPWACore/Generated/BridgeJSData.swift from the
# canonical bridge runtime at Sources/SwiftPWACore/Resources/bridge.js.
#
# bridge.js is base64-embedded into a Swift source rather than shipped as a
# SwiftPM resource because a SwiftPM resource bundle can't travel inside an app
# bundle: the generated `Bundle.module` accessor looks for it beside
# `Bundle.main.bundleURL`, which for a `.app` is the bundle *root* — the one
# place codesign refuses to seal ("unsealed contents present in the bundle
# root"). So every `.app` / AppImage / portable .exe read bridge.js out of the
# build machine's `.build/` and crashed on launch anywhere else. Embedding the
# text makes the runtime self-contained on every platform, and lets the CLI's
# Android APK staging use the same copy from a prebuilt single-file binary.
#
# Run this whenever bridge.js changes; `swift test` fails on drift.
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
SRC="$ROOT/Sources/SwiftPWACore/Resources/bridge.js"
OUT="$ROOT/Sources/SwiftPWACore/Generated/BridgeJSData.swift"
mkdir -p "$(dirname "$OUT")"

# base64, stripped of any line wrapping (BSD and GNU base64 differ).
b64="$(base64 < "$SRC" | tr -d '\n')"

{
  echo "// Generated by Scripts/regenerate-bridge-js.sh — DO NOT EDIT BY HAND."
  echo "//"
  echo "// The canonical bridge runtime (Sources/SwiftPWACore/Resources/bridge.js),"
  echo "// base64-embedded so an app bundle carries it in the binary instead of in a"
  echo "// SwiftPM resource bundle — one can't live inside a signed .app (see"
  echo "// Scripts/regenerate-bridge-js.sh). Regenerate with that script when"
  echo "// bridge.js changes."
  echo "import Foundation"
  echo ""
  echo "package enum BridgeJSData {"
  echo "    /// The bridge.js text, decoded from the embedded base64."
  echo "    package static let source: String = {"
  echo "        guard let data = Data(base64Encoded: \"$b64\"),"
  echo "              let text = String(data: data, encoding: .utf8)"
  echo "        else { fatalError(\"BridgeJSData: corrupt embedded bridge.js\") }"
  echo "        return text"
  echo "    }()"
  echo "}"
} > "$OUT"

echo "wrote $OUT ($(wc -c < "$OUT") bytes)"
