#!/usr/bin/env bash
#
# Regenerate Sources/SwiftPWACLISupport/Generated/BridgeJSData.swift from the
# canonical bridge runtime at Sources/SwiftPWACore/Resources/bridge.js.
#
# bridge.js is base64-embedded into a CLI-side Swift source so the Android
# bundler can stage it into the APK even from a PREBUILT single-file `swift-pwa`
# binary. Previously the bundler called `SwiftPWACore.BridgeScript.source()`,
# which reads `Bundle.module` — and a single-file binary has no co-located
# `SwiftPWACore.bundle`, so `build --target android` trapped with
# "could not load resource bundle … swift-pwa_SwiftPWACore.bundle".
#
# Run this whenever bridge.js changes (CI verifies it's in sync). The runtime
# backends still read bridge.js from Core's bundle directly — this embedded
# copy is only for the CLI's APK-staging step.
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
SRC="$ROOT/Sources/SwiftPWACore/Resources/bridge.js"
OUT="$ROOT/Sources/SwiftPWACLISupport/Generated/BridgeJSData.swift"
mkdir -p "$(dirname "$OUT")"

# base64, stripped of any line wrapping (BSD and GNU base64 differ).
b64="$(base64 < "$SRC" | tr -d '\n')"

{
  echo "// Generated by Scripts/regenerate-bridge-js.sh — DO NOT EDIT BY HAND."
  echo "//"
  echo "// The canonical bridge runtime (Sources/SwiftPWACore/Resources/bridge.js),"
  echo "// base64-embedded so the Android bundler stages it into the APK even from a"
  echo "// prebuilt single-file swift-pwa binary (no SwiftPM resource bundle, hence no"
  echo "// SwiftPWACore Bundle.module to read). Regenerate via"
  echo "// Scripts/regenerate-bridge-js.sh when bridge.js changes."
  echo "import Foundation"
  echo ""
  echo "enum BridgeJSData {"
  echo "    /// The bridge.js text, decoded from the embedded base64."
  echo "    static let source: String = {"
  echo "        guard let data = Data(base64Encoded: \"$b64\"),"
  echo "              let text = String(data: data, encoding: .utf8)"
  echo "        else { fatalError(\"BridgeJSData: corrupt embedded bridge.js\") }"
  echo "        return text"
  echo "    }()"
  echo "}"
} > "$OUT"

echo "wrote $OUT ($(wc -c < "$OUT") bytes)"
