#!/usr/bin/env bash
#
# Regenerate Sources/SwiftPWACLISupport/Generated/GradleWrapperData.swift from
# the vendored Gradle wrapper under Vendor/gradle-wrapper/.
#
# The wrapper (gradlew, gradlew.bat, gradle-wrapper.jar/.properties, pinned to
# a specific Gradle version) is base64-embedded into a Swift source so the
# Android bundler can stage `./gradlew` even from a PREBUILT single-file
# `swift-pwa` binary — one that ships no SwiftPM resource bundle beside it.
#
# Run this only when bumping the pinned Gradle version: drop the new wrapper
# files into Vendor/gradle-wrapper/, run `Scripts/regenerate-gradle-wrapper.sh`,
# and commit the regenerated GradleWrapperData.swift alongside them.
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
SRC="$ROOT/Vendor/gradle-wrapper"
OUT="$ROOT/Sources/SwiftPWACLISupport/Generated/GradleWrapperData.swift"
mkdir -p "$(dirname "$OUT")"

# base64, stripped of any line wrapping (BSD and GNU base64 differ).
b64() { base64 < "$1" | tr -d '\n'; }

gradlew="$(b64 "$SRC/gradlew")"
gradlewBat="$(b64 "$SRC/gradlew.bat")"
jar="$(b64 "$SRC/gradle/wrapper/gradle-wrapper.jar")"
props="$(b64 "$SRC/gradle/wrapper/gradle-wrapper.properties")"

{
  echo "// Generated by Scripts/regenerate-gradle-wrapper.sh — DO NOT EDIT BY HAND."
  echo "//"
  echo "// The vendored Gradle wrapper (Vendor/gradle-wrapper/), base64-embedded so"
  echo "// the Android bundler stages \`./gradlew\` even from a prebuilt single-file"
  echo "// swift-pwa binary (no SwiftPM resource bundle required). Regenerate via"
  echo "// Scripts/regenerate-gradle-wrapper.sh after bumping the pinned Gradle version."
  echo "import Foundation"
  echo ""
  echo "enum GradleWrapperData {"
  echo "    /// \`gradlew\` Unix launcher (staged 0755)."
  echo "    static let gradlew = decode(\"$gradlew\")"
  echo "    /// \`gradlew.bat\` Windows launcher."
  echo "    static let gradlewBat = decode(\"$gradlewBat\")"
  echo "    /// \`gradle/wrapper/gradle-wrapper.jar\` bootstrap JAR."
  echo "    static let gradleWrapperJar = decode(\"$jar\")"
  echo "    /// \`gradle/wrapper/gradle-wrapper.properties\` (pins the Gradle version)."
  echo "    static let gradleWrapperProperties = decode(\"$props\")"
  echo ""
  echo "    private static func decode(_ base64: String) -> Data {"
  echo "        // Force-unwrap is safe: the strings are generated from real files."
  echo "        Data(base64Encoded: base64)!"
  echo "    }"
  echo "}"
} > "$OUT"

echo "wrote $OUT ($(wc -c < "$OUT") bytes)"
